/*
 * Copyright 2021 George Fitzpatrick
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.georgefitzpatrick.cloud.autoconfigure.zuul.fingerprint.ssl;

import com.georgefitzpatrick.cloud.autoconfigure.zuul.fingerprint.ssl.extension.ECPointFormats;
import com.georgefitzpatrick.cloud.autoconfigure.zuul.fingerprint.ssl.extension.ServerName;
import com.georgefitzpatrick.cloud.autoconfigure.zuul.fingerprint.ssl.extension.SupportedGroups;
import com.georgefitzpatrick.cloud.autoconfigure.zuul.fingerprint.util.ByteBufferParser;
import org.jetbrains.annotations.NotNull;

import java.nio.ByteBuffer;
import java.util.Arrays;

/**
 * @author George Fitzpatrick
 */
public enum SSLExtensionType {

    /* ----- Enumerations ----- */

    UNASSIGNED(-1, ByteBuffer::array),

    // reserved
    RESERVED_0x28(0x28, ByteBuffer::array),
    RESERVED_0x2E(0x2E, ByteBuffer::array),

    // grease
    GREASE_0x0A0A(0x0A0A, ByteBuffer::array),
    GREASE_0x1A1A(0x1A1A, ByteBuffer::array),
    GREASE_0x2A2A(0x2A2A, ByteBuffer::array),
    GREASE_0x3A3A(0x3A3A, ByteBuffer::array),
    GREASE_0x4A4A(0x4A4A, ByteBuffer::array),
    GREASE_0x5A5A(0x5A5A, ByteBuffer::array),
    GREASE_0x6A6A(0x6A6A, ByteBuffer::array),
    GREASE_0x7A7A(0x7A7A, ByteBuffer::array),
    GREASE_0x8A8A(0x8A8A, ByteBuffer::array),
    GREASE_0x9A9A(0x9A9A, ByteBuffer::array),
    GREASE_0xAAAA(0xAAAA, ByteBuffer::array),
    GREASE_0xBABA(0xBABA, ByteBuffer::array),
    GREASE_0xCACA(0xCACA, ByteBuffer::array),
    GREASE_0xDADA(0xDADA, ByteBuffer::array),
    GREASE_0xEAEA(0xEAEA, ByteBuffer::array),
    GREASE_0xFAFA(0xFAFA, ByteBuffer::array),

    // private
    PRIVATE_0xFF00(0xFF00, ByteBuffer::array),
    PRIVATE_0xFF02(0xFF02, ByteBuffer::array),
    PRIVATE_0xFF03(0xFF03, ByteBuffer::array),
    PRIVATE_0xFF04(0xFF04, ByteBuffer::array),
    PRIVATE_0xFF05(0xFF05, ByteBuffer::array),
    PRIVATE_0xFF06(0xFF06, ByteBuffer::array),
    PRIVATE_0xFF07(0xFF07, ByteBuffer::array),
    PRIVATE_0xFF08(0xFF08, ByteBuffer::array),
    PRIVATE_0xFF09(0xFF09, ByteBuffer::array),
    PRIVATE_0xFF0A(0xFF0A, ByteBuffer::array),
    PRIVATE_0xFF0B(0xFF0B, ByteBuffer::array),
    PRIVATE_0xFF0C(0xFF0C, ByteBuffer::array),
    PRIVATE_0xFF0D(0xFF0D, ByteBuffer::array),
    PRIVATE_0xFF0E(0xFF0E, ByteBuffer::array),
    PRIVATE_0xFF0F(0xFF0F, ByteBuffer::array),
    PRIVATE_0xFF10(0xFF10, ByteBuffer::array),
    PRIVATE_0xFF11(0xFF11, ByteBuffer::array),
    PRIVATE_0xFF12(0xFF12, ByteBuffer::array),
    PRIVATE_0xFF13(0xFF13, ByteBuffer::array),
    PRIVATE_0xFF14(0xFF14, ByteBuffer::array),
    PRIVATE_0xFF15(0xFF15, ByteBuffer::array),
    PRIVATE_0xFF16(0xFF16, ByteBuffer::array),
    PRIVATE_0xFF17(0xFF17, ByteBuffer::array),
    PRIVATE_0xFF18(0xFF18, ByteBuffer::array),
    PRIVATE_0xFF19(0xFF19, ByteBuffer::array),
    PRIVATE_0xFF1A(0xFF1A, ByteBuffer::array),
    PRIVATE_0xFF1B(0xFF1B, ByteBuffer::array),
    PRIVATE_0xFF1C(0xFF1C, ByteBuffer::array),
    PRIVATE_0xFF1D(0xFF1D, ByteBuffer::array),
    PRIVATE_0xFF1E(0xFF1E, ByteBuffer::array),
    PRIVATE_0xFF1F(0xFF1F, ByteBuffer::array),
    PRIVATE_0xFF20(0xFF20, ByteBuffer::array),
    PRIVATE_0xFF21(0xFF21, ByteBuffer::array),
    PRIVATE_0xFF22(0xFF22, ByteBuffer::array),
    PRIVATE_0xFF23(0xFF23, ByteBuffer::array),
    PRIVATE_0xFF24(0xFF24, ByteBuffer::array),
    PRIVATE_0xFF25(0xFF25, ByteBuffer::array),
    PRIVATE_0xFF26(0xFF26, ByteBuffer::array),
    PRIVATE_0xFF27(0xFF27, ByteBuffer::array),
    PRIVATE_0xFF28(0xFF28, ByteBuffer::array),
    PRIVATE_0xFF29(0xFF29, ByteBuffer::array),
    PRIVATE_0xFF2A(0xFF2A, ByteBuffer::array),
    PRIVATE_0xFF2B(0xFF2B, ByteBuffer::array),
    PRIVATE_0xFF2C(0xFF2C, ByteBuffer::array),
    PRIVATE_0xFF2D(0xFF2D, ByteBuffer::array),
    PRIVATE_0xFF2E(0xFF2E, ByteBuffer::array),
    PRIVATE_0xFF2F(0xFF2F, ByteBuffer::array),
    PRIVATE_0xFF30(0xFF30, ByteBuffer::array),
    PRIVATE_0xFF31(0xFF31, ByteBuffer::array),
    PRIVATE_0xFF32(0xFF32, ByteBuffer::array),
    PRIVATE_0xFF33(0xFF33, ByteBuffer::array),
    PRIVATE_0xFF34(0xFF34, ByteBuffer::array),
    PRIVATE_0xFF35(0xFF35, ByteBuffer::array),
    PRIVATE_0xFF36(0xFF36, ByteBuffer::array),
    PRIVATE_0xFF37(0xFF37, ByteBuffer::array),
    PRIVATE_0xFF38(0xFF38, ByteBuffer::array),
    PRIVATE_0xFF39(0xFF39, ByteBuffer::array),
    PRIVATE_0xFF3A(0xFF3A, ByteBuffer::array),
    PRIVATE_0xFF3B(0xFF3B, ByteBuffer::array),
    PRIVATE_0xFF3C(0xFF3C, ByteBuffer::array),
    PRIVATE_0xFF3D(0xFF3D, ByteBuffer::array),
    PRIVATE_0xFF3E(0xFF3E, ByteBuffer::array),
    PRIVATE_0xFF3F(0xFF3F, ByteBuffer::array),
    PRIVATE_0xFF40(0xFF40, ByteBuffer::array),
    PRIVATE_0xFF41(0xFF41, ByteBuffer::array),
    PRIVATE_0xFF42(0xFF42, ByteBuffer::array),
    PRIVATE_0xFF43(0xFF43, ByteBuffer::array),
    PRIVATE_0xFF44(0xFF44, ByteBuffer::array),
    PRIVATE_0xFF45(0xFF45, ByteBuffer::array),
    PRIVATE_0xFF46(0xFF46, ByteBuffer::array),
    PRIVATE_0xFF47(0xFF47, ByteBuffer::array),
    PRIVATE_0xFF48(0xFF48, ByteBuffer::array),
    PRIVATE_0xFF49(0xFF49, ByteBuffer::array),
    PRIVATE_0xFF4A(0xFF4A, ByteBuffer::array),
    PRIVATE_0xFF4B(0xFF4B, ByteBuffer::array),
    PRIVATE_0xFF4C(0xFF4C, ByteBuffer::array),
    PRIVATE_0xFF4D(0xFF4D, ByteBuffer::array),
    PRIVATE_0xFF4E(0xFF4E, ByteBuffer::array),
    PRIVATE_0xFF4F(0xFF4F, ByteBuffer::array),
    PRIVATE_0xFF50(0xFF50, ByteBuffer::array),
    PRIVATE_0xFF51(0xFF51, ByteBuffer::array),
    PRIVATE_0xFF52(0xFF52, ByteBuffer::array),
    PRIVATE_0xFF53(0xFF53, ByteBuffer::array),
    PRIVATE_0xFF54(0xFF54, ByteBuffer::array),
    PRIVATE_0xFF55(0xFF55, ByteBuffer::array),
    PRIVATE_0xFF56(0xFF56, ByteBuffer::array),
    PRIVATE_0xFF57(0xFF57, ByteBuffer::array),
    PRIVATE_0xFF58(0xFF58, ByteBuffer::array),
    PRIVATE_0xFF59(0xFF59, ByteBuffer::array),
    PRIVATE_0xFF5A(0xFF5A, ByteBuffer::array),
    PRIVATE_0xFF5B(0xFF5B, ByteBuffer::array),
    PRIVATE_0xFF5C(0xFF5C, ByteBuffer::array),
    PRIVATE_0xFF5D(0xFF5D, ByteBuffer::array),
    PRIVATE_0xFF5E(0xFF5E, ByteBuffer::array),
    PRIVATE_0xFF5F(0xFF5F, ByteBuffer::array),
    PRIVATE_0xFF60(0xFF60, ByteBuffer::array),
    PRIVATE_0xFF61(0xFF61, ByteBuffer::array),
    PRIVATE_0xFF62(0xFF62, ByteBuffer::array),
    PRIVATE_0xFF63(0xFF63, ByteBuffer::array),
    PRIVATE_0xFF64(0xFF64, ByteBuffer::array),
    PRIVATE_0xFF65(0xFF65, ByteBuffer::array),
    PRIVATE_0xFF66(0xFF66, ByteBuffer::array),
    PRIVATE_0xFF67(0xFF67, ByteBuffer::array),
    PRIVATE_0xFF68(0xFF68, ByteBuffer::array),
    PRIVATE_0xFF69(0xFF69, ByteBuffer::array),
    PRIVATE_0xFF6A(0xFF6A, ByteBuffer::array),
    PRIVATE_0xFF6B(0xFF6B, ByteBuffer::array),
    PRIVATE_0xFF6C(0xFF6C, ByteBuffer::array),
    PRIVATE_0xFF6D(0xFF6D, ByteBuffer::array),
    PRIVATE_0xFF6E(0xFF6E, ByteBuffer::array),
    PRIVATE_0xFF6F(0xFF6F, ByteBuffer::array),
    PRIVATE_0xFF70(0xFF70, ByteBuffer::array),
    PRIVATE_0xFF71(0xFF71, ByteBuffer::array),
    PRIVATE_0xFF72(0xFF72, ByteBuffer::array),
    PRIVATE_0xFF73(0xFF73, ByteBuffer::array),
    PRIVATE_0xFF74(0xFF74, ByteBuffer::array),
    PRIVATE_0xFF75(0xFF75, ByteBuffer::array),
    PRIVATE_0xFF76(0xFF76, ByteBuffer::array),
    PRIVATE_0xFF77(0xFF77, ByteBuffer::array),
    PRIVATE_0xFF78(0xFF78, ByteBuffer::array),
    PRIVATE_0xFF79(0xFF79, ByteBuffer::array),
    PRIVATE_0xFF7A(0xFF7A, ByteBuffer::array),
    PRIVATE_0xFF7B(0xFF7B, ByteBuffer::array),
    PRIVATE_0xFF7C(0xFF7C, ByteBuffer::array),
    PRIVATE_0xFF7D(0xFF7D, ByteBuffer::array),
    PRIVATE_0xFF7E(0xFF7E, ByteBuffer::array),
    PRIVATE_0xFF7F(0xFF7F, ByteBuffer::array),
    PRIVATE_0xFF80(0xFF80, ByteBuffer::array),
    PRIVATE_0xFF81(0xFF81, ByteBuffer::array),
    PRIVATE_0xFF82(0xFF82, ByteBuffer::array),
    PRIVATE_0xFF83(0xFF83, ByteBuffer::array),
    PRIVATE_0xFF84(0xFF84, ByteBuffer::array),
    PRIVATE_0xFF85(0xFF85, ByteBuffer::array),
    PRIVATE_0xFF86(0xFF86, ByteBuffer::array),
    PRIVATE_0xFF87(0xFF87, ByteBuffer::array),
    PRIVATE_0xFF88(0xFF88, ByteBuffer::array),
    PRIVATE_0xFF89(0xFF89, ByteBuffer::array),
    PRIVATE_0xFF8A(0xFF8A, ByteBuffer::array),
    PRIVATE_0xFF8B(0xFF8B, ByteBuffer::array),
    PRIVATE_0xFF8C(0xFF8C, ByteBuffer::array),
    PRIVATE_0xFF8D(0xFF8D, ByteBuffer::array),
    PRIVATE_0xFF8E(0xFF8E, ByteBuffer::array),
    PRIVATE_0xFF8F(0xFF8F, ByteBuffer::array),
    PRIVATE_0xFF90(0xFF90, ByteBuffer::array),
    PRIVATE_0xFF91(0xFF91, ByteBuffer::array),
    PRIVATE_0xFF92(0xFF92, ByteBuffer::array),
    PRIVATE_0xFF93(0xFF93, ByteBuffer::array),
    PRIVATE_0xFF94(0xFF94, ByteBuffer::array),
    PRIVATE_0xFF95(0xFF95, ByteBuffer::array),
    PRIVATE_0xFF96(0xFF96, ByteBuffer::array),
    PRIVATE_0xFF97(0xFF97, ByteBuffer::array),
    PRIVATE_0xFF98(0xFF98, ByteBuffer::array),
    PRIVATE_0xFF99(0xFF99, ByteBuffer::array),
    PRIVATE_0xFF9A(0xFF9A, ByteBuffer::array),
    PRIVATE_0xFF9B(0xFF9B, ByteBuffer::array),
    PRIVATE_0xFF9C(0xFF9C, ByteBuffer::array),
    PRIVATE_0xFF9D(0xFF9D, ByteBuffer::array),
    PRIVATE_0xFF9E(0xFF9E, ByteBuffer::array),
    PRIVATE_0xFF9F(0xFF9F, ByteBuffer::array),
    PRIVATE_0xFFA0(0xFFA0, ByteBuffer::array),
    PRIVATE_0xFFA1(0xFFA1, ByteBuffer::array),
    PRIVATE_0xFFA2(0xFFA2, ByteBuffer::array),
    PRIVATE_0xFFA3(0xFFA3, ByteBuffer::array),
    PRIVATE_0xFFA4(0xFFA4, ByteBuffer::array),
    PRIVATE_0xFFA5(0xFFA5, ByteBuffer::array),
    PRIVATE_0xFFA6(0xFFA6, ByteBuffer::array),
    PRIVATE_0xFFA7(0xFFA7, ByteBuffer::array),
    PRIVATE_0xFFA8(0xFFA8, ByteBuffer::array),
    PRIVATE_0xFFA9(0xFFA9, ByteBuffer::array),
    PRIVATE_0xFFAA(0xFFAA, ByteBuffer::array),
    PRIVATE_0xFFAB(0xFFAB, ByteBuffer::array),
    PRIVATE_0xFFAC(0xFFAC, ByteBuffer::array),
    PRIVATE_0xFFAD(0xFFAD, ByteBuffer::array),
    PRIVATE_0xFFAE(0xFFAE, ByteBuffer::array),
    PRIVATE_0xFFAF(0xFFAF, ByteBuffer::array),
    PRIVATE_0xFFB0(0xFFB0, ByteBuffer::array),
    PRIVATE_0xFFB1(0xFFB1, ByteBuffer::array),
    PRIVATE_0xFFB2(0xFFB2, ByteBuffer::array),
    PRIVATE_0xFFB3(0xFFB3, ByteBuffer::array),
    PRIVATE_0xFFB4(0xFFB4, ByteBuffer::array),
    PRIVATE_0xFFB5(0xFFB5, ByteBuffer::array),
    PRIVATE_0xFFB6(0xFFB6, ByteBuffer::array),
    PRIVATE_0xFFB7(0xFFB7, ByteBuffer::array),
    PRIVATE_0xFFB8(0xFFB8, ByteBuffer::array),
    PRIVATE_0xFFB9(0xFFB9, ByteBuffer::array),
    PRIVATE_0xFFBA(0xFFBA, ByteBuffer::array),
    PRIVATE_0xFFBB(0xFFBB, ByteBuffer::array),
    PRIVATE_0xFFBC(0xFFBC, ByteBuffer::array),
    PRIVATE_0xFFBD(0xFFBD, ByteBuffer::array),
    PRIVATE_0xFFBE(0xFFBE, ByteBuffer::array),
    PRIVATE_0xFFBF(0xFFBF, ByteBuffer::array),
    PRIVATE_0xFFC0(0xFFC0, ByteBuffer::array),
    PRIVATE_0xFFC1(0xFFC1, ByteBuffer::array),
    PRIVATE_0xFFC2(0xFFC2, ByteBuffer::array),
    PRIVATE_0xFFC3(0xFFC3, ByteBuffer::array),
    PRIVATE_0xFFC4(0xFFC4, ByteBuffer::array),
    PRIVATE_0xFFC5(0xFFC5, ByteBuffer::array),
    PRIVATE_0xFFC6(0xFFC6, ByteBuffer::array),
    PRIVATE_0xFFC7(0xFFC7, ByteBuffer::array),
    PRIVATE_0xFFC8(0xFFC8, ByteBuffer::array),
    PRIVATE_0xFFC9(0xFFC9, ByteBuffer::array),
    PRIVATE_0xFFCA(0xFFCA, ByteBuffer::array),
    PRIVATE_0xFFCB(0xFFCB, ByteBuffer::array),
    PRIVATE_0xFFCC(0xFFCC, ByteBuffer::array),
    PRIVATE_0xFFCD(0xFFCD, ByteBuffer::array),
    PRIVATE_0xFFCE(0xFFCE, ByteBuffer::array),
    PRIVATE_0xFFCF(0xFFCF, ByteBuffer::array),
    PRIVATE_0xFFD0(0xFFD0, ByteBuffer::array),
    PRIVATE_0xFFD1(0xFFD1, ByteBuffer::array),
    PRIVATE_0xFFD2(0xFFD2, ByteBuffer::array),
    PRIVATE_0xFFD3(0xFFD3, ByteBuffer::array),
    PRIVATE_0xFFD4(0xFFD4, ByteBuffer::array),
    PRIVATE_0xFFD5(0xFFD5, ByteBuffer::array),
    PRIVATE_0xFFD6(0xFFD6, ByteBuffer::array),
    PRIVATE_0xFFD7(0xFFD7, ByteBuffer::array),
    PRIVATE_0xFFD8(0xFFD8, ByteBuffer::array),
    PRIVATE_0xFFD9(0xFFD9, ByteBuffer::array),
    PRIVATE_0xFFDA(0xFFDA, ByteBuffer::array),
    PRIVATE_0xFFDB(0xFFDB, ByteBuffer::array),
    PRIVATE_0xFFDC(0xFFDC, ByteBuffer::array),
    PRIVATE_0xFFDD(0xFFDD, ByteBuffer::array),
    PRIVATE_0xFFDE(0xFFDE, ByteBuffer::array),
    PRIVATE_0xFFDF(0xFFDF, ByteBuffer::array),
    PRIVATE_0xFFE0(0xFFE0, ByteBuffer::array),
    PRIVATE_0xFFE1(0xFFE1, ByteBuffer::array),
    PRIVATE_0xFFE2(0xFFE2, ByteBuffer::array),
    PRIVATE_0xFFE3(0xFFE3, ByteBuffer::array),
    PRIVATE_0xFFE4(0xFFE4, ByteBuffer::array),
    PRIVATE_0xFFE5(0xFFE5, ByteBuffer::array),
    PRIVATE_0xFFE6(0xFFE6, ByteBuffer::array),
    PRIVATE_0xFFE7(0xFFE7, ByteBuffer::array),
    PRIVATE_0xFFE8(0xFFE8, ByteBuffer::array),
    PRIVATE_0xFFE9(0xFFE9, ByteBuffer::array),
    PRIVATE_0xFFEA(0xFFEA, ByteBuffer::array),
    PRIVATE_0xFFEB(0xFFEB, ByteBuffer::array),
    PRIVATE_0xFFEC(0xFFEC, ByteBuffer::array),
    PRIVATE_0xFFED(0xFFED, ByteBuffer::array),
    PRIVATE_0xFFEE(0xFFEE, ByteBuffer::array),
    PRIVATE_0xFFEF(0xFFEF, ByteBuffer::array),
    PRIVATE_0xFFF0(0xFFF0, ByteBuffer::array),
    PRIVATE_0xFFF1(0xFFF1, ByteBuffer::array),
    PRIVATE_0xFFF2(0xFFF2, ByteBuffer::array),
    PRIVATE_0xFFF3(0xFFF3, ByteBuffer::array),
    PRIVATE_0xFFF4(0xFFF4, ByteBuffer::array),
    PRIVATE_0xFFF5(0xFFF5, ByteBuffer::array),
    PRIVATE_0xFFF6(0xFFF6, ByteBuffer::array),
    PRIVATE_0xFFF7(0xFFF7, ByteBuffer::array),
    PRIVATE_0xFFF8(0xFFF8, ByteBuffer::array),
    PRIVATE_0xFFF9(0xFFF9, ByteBuffer::array),
    PRIVATE_0xFFFA(0xFFFA, ByteBuffer::array),
    PRIVATE_0xFFFB(0xFFFB, ByteBuffer::array),
    PRIVATE_0xFFFC(0xFFFC, ByteBuffer::array),
    PRIVATE_0xFFFD(0xFFFD, ByteBuffer::array),
    PRIVATE_0xFFFE(0xFFFE, ByteBuffer::array),
    PRIVATE_0xFFFF(0xFFFF, ByteBuffer::array),

    // assigned
    SERVER_NAME(0x0, ServerName.PARSER),
    MAX_FRAGMENT_LENGTH(0x1, ByteBuffer::array),
    CLIENT_CERTIFICATE_URL(0x2, ByteBuffer::array),
    TRUSTED_CA_KEYS(0x3, ByteBuffer::array),
    TRUNCATED_HMAC(0x4, ByteBuffer::array),
    STATUS_REQUEST(0x5, ByteBuffer::array),
    USER_MAPPING(0x6, ByteBuffer::array),
    CLIENT_AUTHZ(0x7, ByteBuffer::array),
    SERVER_AUTHZ(0x8, ByteBuffer::array),
    CERT_TYPE(0x9, ByteBuffer::array),
    SUPPORTED_GROUPS(0xA, SupportedGroups.PARSER),
    EC_POINT_FORMATS(0xB, ECPointFormats.PARSER),
    SRP(0xC, ByteBuffer::array),
    SIGNATURE_ALGORITHMS(0xD, ByteBuffer::array),
    USE_SRTP(0xE, ByteBuffer::array),
    HEARTBEAT(0xF, ByteBuffer::array),
    APPLICATION_LAYER_PROTOCOL_NEGOTIATION(0x10, ByteBuffer::array),
    STATUS_REQUEST_V2(0x11, ByteBuffer::array),
    SIGNED_CERTIFICATE_TIMESTAMP(0x12, ByteBuffer::array),
    CLIENT_CERTIFICATE_TYPE(0x13, ByteBuffer::array),
    SERVER_CERTIFICATE_TYPE(0x14, ByteBuffer::array),
    PADDING(0x15, ByteBuffer::array),
    ENCRYPT_THEN_MAC(0x16, ByteBuffer::array),
    EXTENDED_MASTER_SECRET(0x17, ByteBuffer::array),
    TOKEN_BINDING(0x18, ByteBuffer::array),
    CACHED_INFO(0x19, ByteBuffer::array),
    TLS_LTS(0x1A, ByteBuffer::array),
    COMPRESS_CERTIFICATE(0x1B, ByteBuffer::array),
    RECORD_SIZE_LIMIT(0x1C, ByteBuffer::array),
    PWD_PROTECT(0x1D, ByteBuffer::array),
    PWD_CLEAR(0x1E, ByteBuffer::array),
    PASSWORD_SALT(0x1F, ByteBuffer::array),
    TICKET_PINNING(0x20, ByteBuffer::array),
    TLS_CERT_WITH_EXTERN_PSK(0x21, ByteBuffer::array),
    DELEGATED_CREDENTIALS(0x22, ByteBuffer::array),
    SESSION_TICKET(0x23, ByteBuffer::array),
    TLMSP(0x24, ByteBuffer::array),
    TLMSP_PROXYING(0x25, ByteBuffer::array),
    TLMSP_DELEGATE(0x26, ByteBuffer::array),
    SUPPORTED_EKT_CIPHERS(0x27, ByteBuffer::array),
    PRE_SHARED_KEY(0x29, ByteBuffer::array),
    EARLY_DATA(0x2A, ByteBuffer::array),
    SUPPORTED_VERSIONS(0x2B, ByteBuffer::array),
    COOKIE(0x2C, ByteBuffer::array),
    PSK_KEY_EXCHANGE_MODES(0x2D, ByteBuffer::array),
    CERTIFICATE_AUTHORITIES(0x2F, ByteBuffer::array),
    OID_FILTERS(0x30, ByteBuffer::array),
    POST_HANDSHAKE_AUTH(0x31, ByteBuffer::array),
    SIGNATURE_ALGORITHMS_CERT(0x32, ByteBuffer::array),
    KEY_SHARE(0x33, ByteBuffer::array),
    TRANSPARENCY_INFO(0x34, ByteBuffer::array),
    CONNECTION_ID(0x36, ByteBuffer::array),
    EXTERNAL_ID_HASH(0x37, ByteBuffer::array),
    EXTERNAL_SESSION_ID(0x38, ByteBuffer::array),
    QUIC_TRANSPORT_PARAMETERS(0x39, ByteBuffer::array),
    TICKET_REQUEST(0x3A, ByteBuffer::array),
    DNSSEC_CHAIN(0x3B, ByteBuffer::array),
    RENEGOTIATION_INFO(0xFF01, ByteBuffer::array);

    /* ----- Fields ----- */

    private final int value;
    private final ByteBufferParser<?> parser;

    /* ----- Constructors ----- */

    SSLExtensionType(int value, ByteBufferParser<?> parser) {
        this.value = value;
        this.parser = parser;
    }

    /* ----- Methods ----- */

    public static @NotNull SSLExtensionType valueOf(int i) {
        return Arrays.stream(values())
                .filter(type -> type.value == i)
                .findFirst()
                .orElse(UNASSIGNED);
    }

    public int value() {
        return value;
    }

    public ByteBufferParser<?> parser() {
        return parser;
    }

}
